<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Dzidek.Net.AutoUpgrade</Title>
    <Copyright>@Dzidek.Net</Copyright>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.0.5</Version>
    <PackageProjectUrl>https://github.com/DzidekDotNet/AutoUpgrade</PackageProjectUrl>
    <RepositoryUrl>https://github.com/DzidekDotNet/AutoUpgrade</RepositoryUrl>
    <PackageLicenseUrl>https://github.com/DzidekDotNet/AutoUpgrade/blob/main/LICENSE</PackageLicenseUrl>
    <PackageTags>DotNetCore, Auto Upgrade, Windows Services</PackageTags>
    <Description>An auto-updating Windows service with the ability to send a new compressed version on demand</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dzidek.Net.AutoUpgrade.Common\Dzidek.Net.AutoUpgrade.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>